#!/usr/bin/env bash
name="e-kilit"
version="master"
description="e-kilit"
source="https://github.com/bayramkarahan/e-kilit/archive/refs/heads/master.zip"
depends="qt5-base"
builddepend=""
group="app.misc"

setup () {
	export PATH=/usr/bin/qt5:$PATH
	cd $SOURCEDIR
	qmake e-kilit.pro
}

build () {
    make
}

package () {
    make INSTALL_ROOT=$DESTDIR install
}

